/**
 * Browser-side API client.
 *
 * Everything goes through `/api/proxy/...` on this origin, so there is no CORS, no
 * API URL in the bundle, and the session travels as a first-party cookie the
 * proxy turns into a bearer token.
 */

"use client";

import type {
  ActivitySummary,
  AssetUpload,
  Athlete,
  HomeSummary,
  PageSpec,
  PageSummary,
  PanelResult,
  PanelSpec,
  PlannedItem,
  PlannedItemImportance,
  PlannedItemKind,
  PrecomputeStatus,
  Registry,
  RouteResult,
  SyncStatus,
  TrainingCalendar,
  UiStrings,
} from "./types";

const LANG = process.env.NEXT_PUBLIC_LANG || "en";

export class ApiError extends Error {
  constructor(readonly status: number, message: string) {
    super(message);
  }

  /** The one error worth branching on: the session is gone, so re-authenticate. */
  get isUnauthorized(): boolean {
    return this.status === 401;
  }
}

async function request<T>(
  path: string,
  init: RequestInit & { query?: Record<string, string> } = {},
): Promise<T> {
  const url = new URL(`/api/proxy${path}`, window.location.origin);
  url.searchParams.set("lang", LANG);
  for (const [key, value] of Object.entries(init.query ?? {})) {
    url.searchParams.set(key, value);
  }

  // A `FormData` body must set its own `content-type`: the boundary is generated by
  // the browser, and naming the type ourselves would send a multipart request whose
  // declared boundary matches nothing in it.
  const isForm = init.body instanceof FormData;
  const response = await fetch(url, {
    ...init,
    headers: {
      ...(init.body && !isForm ? { "content-type": "application/json" } : {}),
      ...init.headers,
    },
  });

  if (!response.ok) {
    // FastAPI puts the useful message in `detail`; fall back to raw text.
    let message = `${response.status} ${response.statusText}`;
    try {
      const body = await response.json();
      if (body?.detail) message = typeof body.detail === "string"
        ? body.detail
        : JSON.stringify(body.detail);
    } catch {
      /* keep the status line */
    }
    throw new ApiError(response.status, message);
  }
  if (response.status === 204) return undefined as T;
  return (await response.json()) as T;
}

// --- Registry --------------------------------------------------------------

let registryCache: Promise<Registry> | null = null;

/** The plot catalogue. Static per language, so fetched once per page load. */
export function getRegistry(): Promise<Registry> {
  registryCache ??= request<Registry>("/registry");
  return registryCache;
}

// --- UI strings ------------------------------------------------------------

let uiStringsCache: Promise<UiStrings> | null = null;

/** The app's wording, translated. Static per language, so fetched once. */
export function getUiStrings(): Promise<UiStrings> {
  uiStringsCache ??= request<UiStrings>("/ui-strings");
  return uiStringsCache;
}

// --- Athlete ---------------------------------------------------------------

export const getAthlete = () => request<Athlete>("/auth/me");

/**
 * Patch the athlete's own self-reported fields.
 *
 * Only the keys passed are sent, and the server leaves absent keys alone — so the
 * widgets can be edited independently without overwriting each other. An explicit
 * `null` still clears a field.
 */
export const updateProfile = (
  changes: Partial<Pick<
    Athlete,
    | "weight_kg" | "birthdate" | "height_cm" | "email"
    | "hr_zone1_end" | "hr_zone2_end" | "hr_zone3_end" | "hr_zone4_end"
    | "hr_max" | "vma_pace_s_per_km"
  >>,
) =>
  request<Athlete>("/auth/me", {
    method: "PATCH",
    body: JSON.stringify(changes),
  });

// --- Home ------------------------------------------------------------------

export const getHomeSummary = () => request<HomeSummary>("/home/summary");

/**
 * The latest activity's route. Separate from the summary because it may have to
 * call Strava for an activity imported before routes were stored, and the cards
 * must not wait on that.
 */
export const getLastActivityRoute = () =>
  request<RouteResult>("/home/last-activity/route");

// --- Activities ------------------------------------------------------------

export const listActivities = (limit = 0) =>
  request<{ activities: ActivitySummary[]; total: number }>("/activities", {
    query: limit ? { limit: String(limit) } : {},
  });

export const startSync = (options: { force?: boolean; max_activities?: number } = {}) =>
  request<{ status: string }>("/activities/sync", {
    method: "POST",
    body: JSON.stringify(options),
  });

export const getSyncStatus = () => request<SyncStatus>("/activities/sync");

/** Any activity's route — the generalized form of `getLastActivityRoute`. */
export const getActivityRoute = (activityId: number) =>
  request<RouteResult>(`/activities/${activityId}/route`);

// --- Background computation ------------------------------------------------

export const getPrecomputeStatus = () => request<PrecomputeStatus>("/precompute");

/**
 * Start the background pass that fits the expensive plots.
 *
 * Safe to call on every connect: a pass over an already-filled cache reads it and
 * finishes immediately. A 409 means one is already running, which is not a problem
 * worth surfacing — the caller can ignore it.
 */
export const startPrecompute = (options: { force?: boolean } = {}) =>
  request<{ status: string }>("/precompute", {
    method: "POST",
    body: JSON.stringify(options),
  });

// --- Images ----------------------------------------------------------------

/** Upload one image; the returned `url` is what an image block stores. */
export const uploadAsset = (file: File) => {
  const form = new FormData();
  form.append("file", file);
  return request<AssetUpload>("/assets", { method: "POST", body: form });
};

// --- Pages -----------------------------------------------------------------

/**
 * Every analysis, defaults first.
 *
 * Also the seeding trigger: the server creates any of the three shipped analyses this
 * athlete is missing before it answers, so a fresh account's first visit to the
 * Analysis screen already has them.
 */
export const listPages = () => request<{ pages: PageSummary[] }>("/pages");

export const getPage = (id: string) => request<PageSpec>(`/pages/${id}`);

export const createPage = (name: string) =>
  request<PageSpec>("/pages", { method: "POST", body: JSON.stringify({ name }) });

export const savePage = (id: string, spec: PageSpec) =>
  request<PageSpec>(`/pages/${id}`, {
    method: "PUT",
    body: JSON.stringify({ spec }),
  });

export const deletePage = (id: string) =>
  request<void>(`/pages/${id}`, { method: "DELETE" });

/** A copy is always an ordinary analysis — deletable, free to diverge. */
export const duplicatePage = (id: string, name?: string) =>
  request<PageSpec>(`/pages/${id}/duplicate`, {
    method: "POST",
    body: JSON.stringify({ name: name ?? null }),
  });

// --- Rendering -------------------------------------------------------------

export const renderPage = (spec: PageSpec, forcePlotIds: string[] = []) =>
  request<{ page_id: string; panels: PanelResult[] }>("/render", {
    method: "POST",
    body: JSON.stringify({ spec, force_plot_ids: forcePlotIds }),
  });

/**
 * What the editor calls on every change: re-render just the panel being edited.
 *
 * `refresh` ignores every cached result and recomputes — the "recompute" action.
 * Everything else reuses whatever was computed before, in memory or in the database.
 */
export const renderPanel = (
  panel: PanelSpec,
  forcePlotIds: string[] = [],
  signal?: AbortSignal,
  refresh = false,
) =>
  request<{ panel: PanelResult }>("/render/panel", {
    method: "POST",
    body: JSON.stringify({
      panel,
      force_plot_ids: forcePlotIds,
      refresh,
      // A recompute the athlete asked for should produce the figure, not a button
      // offering to produce it.
      compute_all: refresh,
    }),
    signal,
  });

// --- Training ----------------------------------------------------------------

/** Planned items and completed activities for one date range, inclusive. */
export const getTrainingCalendar = (start: string, end: string) =>
  request<TrainingCalendar>("/training/calendar", { query: { start, end } });

export const createPlannedItem = (item: {
  kind: PlannedItemKind;
  date: string;
  title: string;
  body: string;
  importance?: PlannedItemImportance;
}) =>
  request<PlannedItem>("/training/planned-items", {
    method: "POST",
    body: JSON.stringify(item),
  });

/** Also what a drag-and-drop move calls, with just `{ date }`. */
export const updatePlannedItem = (
  id: string,
  changes: Partial<Pick<PlannedItem, "date" | "title" | "body" | "importance">>,
) =>
  request<PlannedItem>(`/training/planned-items/${id}`, {
    method: "PATCH",
    body: JSON.stringify(changes),
  });

export const deletePlannedItem = (id: string) =>
  request<void>(`/training/planned-items/${id}`, { method: "DELETE" });
